block:
  friction: 0.5
bullet:
  max_life_steps: 200
  speed: 10
button:
  friction: 0.7
chell:
  jumpspeed: 5
  max_horizontal_speed: 4
  horizontal_speed: 1.2
  ray_zoom: 10000
launcher:
  steps_per_launch: 50
pin:
  time: 60
stage:
  map_path: ../maps/
world:
  gravity_y: -9.800000000000001
  gravity_x: 0
gameloop:
  fps: 120